### PR TITLE
Add unit tests for relevant filter plugins and also fix warnings

### LINKED ISSUE #798: ansible functions should have unit tests
All of the functions in `linchpin/provision/filter_plugins` and `linchpin/provision/library` need unit tests

### PR DESCRIPTION
**Pull request by samvarankashyap**
$subject
fixes #798

### CODE REVIEW

**Comment by 14rcole** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
downstream tests failing
https://jenkins-continuous-infra.cloud.continuous-infra.upshift.redhat.com/job/ci-linchpin/1057/artifact/linchpin/centos7_logs/dummy.log
```
Error: 
linchpin command not found
```
@p3ck : Any clue why the container does not have linchpin ?

**Comment by p3ck** [comment]
From the install log:
```
Installing collected packages: PyYAML, jinja2, configparser, dictdiffer, websocket-client, oauthlib, requests-oauthlib, adal, pyasn1-modules, cachetools, rsa, google-auth, kubernetes, python-string-utils, ruamel.ordereddict, ruamel.yaml, openshift, smmap2, gitdb2, gitpython, docker-pycreds, docker-py, linchpin

  Found existing installation: PyYAML 3.12

Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

You are using pip version 19.0.3, however version 19.1.1 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by p3ck** [comment]
the script linchpin-install.sh should probably have a set -e added so these fail at install stage.

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test] failed on aws_eip retrying

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[test]

File: config/Dockerfiles/linchpin-install.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@ make pip_install.sh
 ./pip_install.sh
 popd
 
-pip install .
+pip install . --ignore-installed
```
Comment (14rcole) [inline config/Dockerfiles/linchpin-install.sh]: Should you add `--ignore-installed` to the other `pip install` commands as well?

File: linchpin/FilterUtils/FilterUtils.py [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+
+try:
+    import libvirt
+    from xml.dom import minidom
+    from xml.etree.ElementTree import fromstring
+except Exception as e:
+    print(e)
+
+
+def add_res_type(hosts, res_type):
```
Comment (14rcole) [inline linchpin/FilterUtils/FilterUtils.py]: What's the purpose of moving all of these functions?  Are we unable to test them otherwise?

File: config/Dockerfiles/linchpin-install.sh (hunk 1 above)
Comment (samvarankashyap) [reply config/Dockerfiles/linchpin-install.sh]: I would like to just overwrite the packages for linchpin.
Though it is safe in the container I would not recommend it since there can be accidental overwrites.

File: linchpin/FilterUtils/FilterUtils.py (hunk 2 above)
Comment (samvarankashyap) [reply linchpin/FilterUtils/FilterUtils.py]: Yes.
I tried importing them from their respective files but there was a path resolution issue. 
Further, Since most of the functions are utility based functions they can also be used in other places if consolidated in a sub package.

**Comment by samvarankashyap** [comment]
[test] failing on aws

**Comment by samvarankashyap** [comment]
[test]

**Comment by samvarankashyap** [comment]
[merge]
